[package]
name = "challenge-zettascale"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
clap = "^3"
env_logger = "0.10.0"
rand = "0.8.5"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master" }
